inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails:
  Enabled: true
