inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $redis

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
