dist: trusty
language: ruby
rvm:
- 2.4.1

bundler_args: --without production
cache: bundler

env:
- RAILS_ENV=test

jobs:
  include:
  - stage: test
    addons:
      postgresql: "9.6"
    before_script:
    - psql -c "CREATE DATABASE magara_test;" -U postgres
    - psql -c "CREATE USER magara WITH PASSWORD 'magara';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE magara_test TO magara;" -U postgres
    - psql -c "ALTER USER magara WITH SUPERUSER;" -U postgres
    - bundle exec rails db:setup
    script: bundle exec rspec
    after_script:
    - bundle exec rails db:drop
