dist: xenial
language: ruby

bundler_args: --without production
cache:
 directories:
 - vendor/bundle/
 - node_modules/

jobs:
  include:
  - stage: Code analysis
    script: bundle exec rubocop
  - script: bundle exec scss-lint
  - script: bundle exec brakeman

  - stage: Tests
    env:
    - RAILS_ENV=test
    services:
    - postgresql
    - elasticsearch
    before_script:
    # Add user and database with their previleges for PostgreSQL
    - psql -c "CREATE DATABASE magara_test;" -U postgres
    - psql -c "CREATE USER magara WITH PASSWORD 'magara';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE magara_test TO magara;" -U postgres
    - psql -c "ALTER USER magara WITH SUPERUSER;" -U postgres
    # Install JavaScript dependencies
    - yarn install
    # Compile assets and setup database
    - bundle exec rails assets:precompile
    - bundle exec rails db:setup
    script: bundle exec rspec

  - stage: Build
    if: branch = master
    script: docker build -t magara --build-arg RAILS_MASTER_KEY=$RAILS_MATER_KEY .
