dist: xenial
language: ruby

bundler_args: --without production
cache:
 directories:
 - vendor/bundle/
 - node_modules/

jobs:
  include:
  - stage: Code analysis
    script: bundle exec rubocop
  - script: bundle exec scss-lint
  - script: bundle exec brakeman

  - stage: Tests
    env:
    - RAILS_ENV=test

    services:
    - postgresql
    - elasticsearch

    before_script:
    # Add user and database with their previleges for PostgreSQL
    - psql -c "CREATE DATABASE magara_test;" -U postgres
    - psql -c "CREATE USER magara WITH PASSWORD 'magara';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE magara_test TO magara;" -U postgres
    - psql -c "ALTER USER magara WITH SUPERUSER;" -U postgres
    # Install JavaScript dependencies
    - yarn install
    # Compile assets and setup database
    - bundle exec rails assets:precompile
    - bundle exec rails db:setup
    script: bundle exec rspec

  - stage: Build container
    if: branch = master

    addons:
      apt:
        packages:
        - docker-ce

    before_install:
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

    before_script:
    - echo $RAILS_MASTER_KEY > /home/travis/master.key
    # TODO: Login on Docker Hub
    script: DOCKER_BUILDKIT=1 docker build --quiet --secret id=master,src=/home/travis/master.key --tag magara .
    after_script:
    - rm /home/travis/master.key
    # TODO: Push the container
    # TODO: Logout from Docker Hub
