dist: trusty
language: ruby
rvm:
- 2.5.1

bundler_args: --without production
cache:
 directories:
 - vendor/bundle/
 - node_modules/

jobs:
  include:
  - stage: code-analysis
    script: bundle exec rubocop
  - script: bundle exec scss-lint
  - script: bundle exec brakeman --format text

  - stage: test
    env:
    - RAILS_ENV=test
    addons:
      postgresql: "9.6"
    services:
    - elasticsearch
    before_script:
    # Add user and database with their previleges for PostgreSQL
    - psql -c "CREATE DATABASE magara_test;" -U postgres
    - psql -c "CREATE USER magara WITH PASSWORD 'magara';" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE magara_test TO magara;" -U postgres
    - psql -c "ALTER USER magara WITH SUPERUSER;" -U postgres
    # Install JavaScript dependencies
    - yarn install
    # Setup assets and database
    - bundle exec rails assets:precompile
    - bundle exec rails db:setup
    script: bundle exec rspec
