dist: xenial
language: ruby

bundler_args: --without production
cache:
  bundler: true
  directories:
    - node_modules

notifications:
  slack:
    secure: E+oanXltamBcA9OTCvu0BiFzEyKWGNzBejKUVUnJ4l9lKysItfzTXSbPTD+I40brths58YNSmVVy0Ui5j0JI59Iik4asXvX2pa/LYQyn4dXOmf03+HM68GZyQkwpuwGU7L2zFPnAhvXvBoLD8oYoRiH+ZsVwUyP29Mh8pqEedcyT+YLo6trAy4nNC8nPucmHl2Uq8MViDmtXkRgOR8xelXCeSQT8dW67vO6QBc9E5GEHJC1zPzlrztdQ4cvfPTymM8v6KtFdCCVDo+iXTGTJcaWxsXFfQ2gzVHrKuZITTifzQUirndUlZLWwHePlMVZGyTUhJgjJyGYfPHPkHdwAYqUME0AaPGUdEAJskBDragLFHUn5F5GUtH97NvQU9xD99wmB4AsYpoNAjVhY5xxHa7gu6D40epc5ZneffsAJkC7r8RT5Yop45tRR44z5vLqiVMxBpZLC04owBQ5XHbfQEHmcMfd20sRWxm4WOFK0+nmA4DozrKi7TO1SObuxxdL7AqBNNxENwTyjnWDcjnseHs7plf8rU5X6oD+P7B9fxmUzSexFUta4LLb99a9CSOENFBaocykDl9yISnpFUh/xEH4ItjyJxkbNYnTcnihGvb1utvP5AKspoknsCscyc5kqJRYJ4RL0fSyDc3fMJKsrAanHqRu1kAkpoG6+zlhyzEE=

jobs:
  include:
    - stage: Code analysis
      script: bundle exec rubocop
    - script: bundle exec scss-lint
    - script: bundle exec brakeman

    - stage: Tests

      services:
        - postgresql
        - elasticsearch

      before_script:
        # Add user and database with their previleges for PostgreSQL
        - psql -c "CREATE DATABASE magara_test;" -U postgres
        - psql -c "CREATE USER magara WITH PASSWORD 'magara';" -U postgres
        - psql -c "GRANT ALL PRIVILEGES ON DATABASE magara_test TO magara;" -U postgres
        - psql -c "ALTER USER magara WITH SUPERUSER;" -U postgres
        # Create magara_test database and migrate
        - bundle exec rails db:setup
      script: bundle exec rspec

    - stage: Build container
      if: tag IS present

      addons:
        apt:
          packages:
            - docker-ce

      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

      before_script:
        - echo $RAILS_MASTER_KEY > /home/travis/master.key
      script: DOCKER_BUILDKIT=1 docker build --quiet \
        --compress --secret id=master,src=/home/travis/master.key \
        --tag magara/magara:latest --tag magara/magara:$TRAVIS_TAG .
      after_script:
        - echo $DOCKER_PASSWORD | docker login --username=$DOCKER_USERNAME --password-stdin
        - rm /home/travis/master.key
        - docker push magara/magara:latest
        - docker push magara/magara:$TRAVIS_TAG
        - docker logout

    - stage: Deploy
      if: tag IS present

      script: skip

      deploy:
        - provider: elasticbeanstalk

          access_key_id: AKIAYA3ACZRSDEUW6IPF
          secret_access_key:
            secure: Z+xaZ90gTlpZyJiAkyViUAQFqs3RkpNKIAEao+eryi571PSgrOYx77cyhOffTgs/Yd9H0ikzcKh7dK7V2qQfoUCEpR2dxbdZ5q2UQxHgpttWbs/aoCXaRWoG1qXmpWEKbdCv+c+eXlDEjJ96WM/7BlYWipEqDDSCrUJutqsLf3QpW8N45Rilx7QIF4TesiOTqrCyYIx6joMNT/VDpG75cIcsPL1uPeFrPNm3cJRZTZf9oJMsp7ham6CeihKBxptkUiEeJ0dkyCsCvuoxFPqPoLiODi7f7wNIhBUWHjuVpndnfJr5r5gPLybvPE9FyiIgtsJukgMtEqS9mSJFO9ZTFOGSx2F/Ihm1JLZazYRLiy0x49pM3jyW9p36t7cd20/DupS0H/q2JswK4Nrlj5wxvBXvJ8leQoSssGGB06ga1pUJ0tzISRuGkEhek8Vj+n8TyNtG9sQWALJvVVdj3HDG4EujCDBt/0SfngwFMzPAloqvpi49+by6y3C1PISsGalIUqZt+PFk8BmxH48KG0MWgaBvo8MhseUsbGjetr50ZgQUVNkqJYYh/+6wio4OIyPkdHltG9y6zn9zqp0XIDZj18Cs15UrI+nAKVV4pHHI0ddJlMr/O8E7TIuP0yLd7ImY5H9+zCeFbmG113nlrTLD3UecCJcX94A9h42/xlqYE7s=

          region: us-west-2
          app: Mağara
          env: magara-production

          on:
            tags: true
