version: "3"

services:
  postgres:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_USER: magara
      POSTGRES_PASSWORD: magara
      POSTGRES_DB: magara_development
    ports:
    - "5432:5432"
    networks:
    - backend

  elasticsearch:
    image: elasticsearch:6.6.1
    environment:
      "discovery.type": single-node
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
    - backend

  kibana:
    image: kibana:6.6.1
    ports:
    - "5601:5601"
    networks:
    - backend

networks:
  backend:
